#!/usr/bin/env python3
'''This module contains the function for the optimization
'''

import numpy as np

import scipy.optimize as opt
import matplotlib.pyplot as plt

from tersoff_pot import potential as pot
import potential as pt
import basis_change

def unpk():
    """
    This function unpacks the data in the file energy_temp.txt and plots
    it as a histogram. The file is generated by print_fun during the (see below)
    iterations of basinhopping

    Returns
    -------
    e : array-like
        Array of energies.

    n : array-like
        Number of times each energy has been found by the minimisation.
    """
    e=list()
    with open('energy_temp.txt') as f:
        for i in f.readlines():
            e.append(float(i))
    e = np.array(e)
    emin = e.min()
    n = np.histogram(e,bins=1000,range=(1.001*e.min(),0.9*e.min()))[0]
    e = np.linspace(1.001*e.min(),0.9*e.min(),1000)
    plt.figure()
    plt.plot(e, n)
    plt.ylim(0, n.max())
    plt.show()
    return e, n

def var_unpack(filename):
    """
    This function unpacks the data from the file containing all the atomic positions
    of the optimised structure.

    Parameters
    ----------
    filename: str;
    Name of the file from which the function reads the atomic positions and
    lattice parameters

    Returns
    -------
 #   x0 : array-like (3, 1)
        The position of the 1st atom in the unit cell (0, 0, 0), which is a para-
        -meter of the potential function.

    variables : array-like (3*N + 3, 1)
        The first (3N - 3) elements are the positions of the remaining atoms and
        the 6 last elements are the lattice parameters (a, b, c, θ, φ, ψ)
    """

    #Extract data from file
    with open(filename, 'r') as var:
        var_lines = var.readlines()

    var_lines = [j.strip('\n') for j in var_lines] #Remove \n
    var_lines = [j.split(': ') for j in var_lines]
    del(var_lines[6])

    var = np.array([])

    for i in range(len(var_lines)):
        A = var_lines[i][1]
        if i not in (3, 4, 5):
            A = A[1: -1]
        A = A.split()
        A = np.array(A, dtype=float)
        var = np.append(var, A)

    #Defining lattice parameters
    lpar = np.zeros(6)

    for j in range(3):
        lpar[j] = np.sqrt(np.sum(np.square(var[3*j:3*j+3])))
        lpar[j + 3] = var[j + 9]

    #Defining atomic positions
    x0 = var[12:15] #position of 1st atom (0, 0, 0) kept separate for minimisation
    npos = var[15:] #position of remaining atoms

    variables = np.append(npos, lpar)
    return x0, variables

def print_fun(x, f, accepted):
    """This function prints the minimum of the energy found during the basinhopping
    minimization algorithm"""
    f = f
    if int(accepted) == 1:
        print("Minimum E = %.4f eV Y"%f)
    else:
        print("Minimum E = %.4f eV N"%f)
    g=open('energy_temp.txt','a+')
    g.write(str(f)+'\n')
    g.close()

class CubTakeStep(object):
    #This class defines the step routine for basinhooping in the cubic mode
    def __init__(self, stepsize=0.15):
        self.stepsize = stepsize
    def __call__(self, x):
        s = self.stepsize
        x[:-1] += np.random.uniform(-s, s,x[:-1].shape)
        x[-1] += np.random.uniform(-2*s, 2*s)
        return x

class OrthTakeStep(object):
    #This class defines the step routine for basinhooping in the cubic mode
    def __init__(self, stepsize=0.15):
        self.stepsize = stepsize
    def __call__(self, x):
        s = self.stepsize
        x[:-1] += np.random.uniform(-s, s,x[:-1].shape)
        x[-3:] += np.random.uniform(-2*s, 2*s, x[-3:].shape)
        return x

class TetTakeStep(object):
    #This class defines the step routine for basinhooping in the cubic mode
    def __init__(self, stepsize=0.15):
        self.stepsize = stepsize
    def __call__(self, x):
        s = self.stepsize
        x[:-1] += np.random.uniform(-s, s,x[:-1].shape)
        x[-2:] += np.random.uniform(-2*s, 2*s, x[-2].shape)
        return x

class TriTakeStep(object):
        #This class defines the step routine for basinhooping in the triclinic mode
    def __init__(self, stepsize=0.15):
        self.stepsize = stepsize
    def __call__(self, x):
        s = self.stepsize
        x[:-6] += np.random.uniform(-s, s,x[:-6].shape)
        x[-6:-3] += np.random.uniform(-2*s, 2*s,x[-6:-3].shape)
        x[-3:] += np.random.uniform(-s, s,x[-3:].shape)

        return x

def cub_opt(filename,r,bsh,T,it,step):
    """
    	Minimizes the energy of a cubic crystal structure read from filename.
    	------------------------------------------------------------------------

    	Parameters:
        -----------
            filename: str;
            Name of the file to read - see Documentation for format
            r: float;
            Radius of the silicon atom in Å
            bsh: bool;
            True or False, depending on whether the user wants to use basinghopping
            or not
            T: float;
            Temperature to be used in the basinhopping minimisation algorithm
            it: int;
            Number of iterations of the basinhopping algorithm
            step: float;
            Stepsize of the basinhopping algorithm

    	Returns:
        -------
    		opt_var: array-like;
            The optimized cartesian coordinates of the 3N-3 atoms in the unit cell
            (excluding the atom in the origin) plus the 6 lattice parameters
    """

    cubtakestep = CubTakeStep(stepsize=step)
    x0, var = var_unpack(filename)
    N = int((len(var) - 3)/3)
    lvar = basis_change.c_l(var)
    atoms = lvar[:-6]
    lpar = lvar[-6:]
    a = lpar[0]

    bnds = list()
    for i in range(3*N-3):
        bnds.append((0,1))
    bnds.append((2*r,6*r))
    bnds=tuple(bnds)

    start = np.append(atoms,a)

    #Minimise potential
    if bsh == True:
        result = opt.basinhopping(pt.cub_fpot,x0=start,niter=int(it),callback=print_fun,
                               T=T,take_step=cubtakestep,minimizer_kwargs={"args":x0,
                               "method":"L-BFGS-B","bounds":bnds,'options':{'maxls'
                               :10000,'ftol':1e-15,'maxcor':100}})
    elif bsh == False:
        result = opt.minimize(pt.cub_fpot,x0=start,method="SLSQP",bounds=bnds,
                                options={'ftol':1e-5,'gtol':1e-3,'eps':1e-12,
                                'maxls':1000})

    opt_var = result.x
    en = result.fun
    print("\nMinimum found: E = %f eV"%en)
    a_opt = opt_var[-1]
    opt_var = np.append(opt_var,(a_opt,a_opt,np.pi/2,np.pi/2,np.pi/2))
    opt_var = basis_change.l_c(opt_var)

    return opt_var

def orth_opt(filename,r,bsh,T,it,step):
    """
    	Minimizes the energy of a triclinic crystal structure read from filename.
    	------------------------------------------------------------------------

    	Parameters:
        -----------
            filename: str;
            Name of the file to read - see Documentation for format
            r: float;
            Radius of the silicon atom in Å
            bsh: bool;
            True or False, depending on whether the user wants to use basinghopping
            or not
            T: float;
            Temperature to be used in the basinhopping minimisation algorithm
            it: int;
            Number of iterations of the basinhopping algorithm
            step: float;
            Stepsize of the basinhopping algorithm

    	Returns:
        -------
    		opt_var: array-like;
            The optimized cartesian coordinates of the 3N-3 atoms in the unit cell
            (excluding the atom in the origin) plus the 6 lattice parameters
    """

    orthtakestep = OrthTakeStep(stepsize=step)
    x0, var = var_unpack(filename)
    N = int((len(var) - 3)/3)
    lvar = basis_change.c_l(var)
    atoms = lvar[:-6]
    lpar = lvar[-6:]
    a = lpar[0]
    b = lpar[1]
    c = lpar[2]

    bnds = list()
    for i in range(3*N-3):
        bnds.append((0,1))
    bnds.append((2*r,6*r))
    bnds.append((2*r,6*r))
    bnds.append((2*r,6*r))

    start = np.append(atoms,(a,b,c))

    #Minimise potential
    if bsh == True:
        result = opt.basinhopping(pt.orth_fpot,x0=start,niter=int(it),callback=print_fun,
                               T=T,take_step=orthtakestep,minimizer_kwargs={"args":x0,
                               "method":"L-BFGS-B","bounds":bnds,'options':{'maxls'
                               :10000,'ftol':1e-15,'maxcor':100}})
    elif bsh == False:
        result = opt.minimize(pt.orth_fpot,x0=start,method="L-BFGS-B",bounds=bnds,
                            args=x0,options={'maxls':1000,'ftol':1e-15,'maxcor':10})
        print(result.message)

    opt_var = result.x
    en = result.fun
    print("\nMinimum found: E = %f eV"%en)
    opt_var = np.append(opt_var,(np.pi/2,np.pi/2,np.pi/2))
    opt_var = basis_change.l_c(opt_var)

    return opt_var

def tet_opt(filename,r,bsh,T,it,step):
    """
    	Minimizes the energy of a triclinic crystal structure read from filename.
    	------------------------------------------------------------------------

    	Parameters:
        -----------
            filename: str;
            Name of the file to read - see Documentation for format
            r: float;
            Radius of the silicon atom in Å
            bsh: bool;
            True or False, depending on whether the user wants to use basinghopping
            or not
            T: float;
            Temperature to be used in the basinhopping minimisation algorithm
            it: int;
            Number of iterations of the basinhopping algorithm
            step: float;
            Stepsize of the basinhopping algorithm

    	Returns:
        -------
    		opt_var: array-like;
            The optimized cartesian coordinates of the 3N-3 atoms in the unit cell
            (excluding the atom in the origin) plus the 6 lattice parameters
    """

    tettakestep = TetTakeStep(stepsize=step)
    x0, var = var_unpack(filename)
    N = int((len(var) - 3)/3)
    lvar = basis_change.c_l(var)
    atoms = lvar[:-6]
    lpar = lvar[-6:]
    a = lpar[0]
    b = lpar[1]

    bnds = list()
    for i in range(3*N-3):
        bnds.append((0,1))
    bnds.append((2*r,6*r))
    bnds.append((2*r,6*r))

    start = np.append(atoms,(a,b))

    #Minimise potential
    if bsh == True:
        result = opt.basinhopping(pt.tet_fpot,x0=start,niter=int(it),callback=print_fun,
                               T=T,take_step=tettakestep,minimizer_kwargs={"args":x0,
                               "method":"L-BFGS-B","bounds":bnds,'options':{'maxls'
                               :10000,'ftol':1e-15,'maxcor':100}})
    elif bsh == False:
        result = opt.minimize(pt.tet_fpot,x0=start,method="L-BFGS-B",bounds=bnds,
                            args=x0,options={'maxls':1000,'ftol':1e-15,'maxcor':10})
        print(result.message)

    opt_var = result.x
    en = result.fun
    print("\nMinimum found: E = %f eV"%en)
    a_opt = opt_var[-2]
    opt_var = np.append(opt_var,(a_opt,np.pi/2,np.pi/2,np.pi/2))
    opt_var = basis_change.l_c(opt_var)

    return opt_var

def tri_opt(filename,r,bsh,T,it,step):
    """
    	Minimizes the energy of a triclinic crystal structure read from filename.
    	------------------------------------------------------------------------

    	Parameters:
        -----------
            filename: str;
            Name of the file to read - see Documentation for format
            r: float;
            Radius of the silicon atom in Å
            bsh: bool;
            True or False, depending on whether the user wants to use basinghopping
            or not
            T: float;
            Temperature to be used in the basinhopping minimisation algorithm
            it: int;
            Number of iterations of the basinhopping algorithm
            step: float;
            Stepsize of the basinhopping algorithm

    	Returns:
        -------
    		opt_var: array-like;
            The optimized cartesian coordinates of the 3N-3 atoms in the unit cell
            (excluding the atom in the origin) plus the 6 lattice parameters
    """

    tritakestep = TriTakeStep(stepsize=step)
    x0, var = var_unpack(filename)
    N = int((len(var) - 3)/3)
    lvar = basis_change.c_l(var)

    bnds = list()
    for i in range(3*N-3):
        bnds.append((0,1))
    bnds.append((2*r,6*r))
    bnds.append((2*r,6*r))
    bnds.append((2*r,6*r))
    bnds.append((np.arcsin(0.666),np.pi))
    bnds.append((np.arcsin(0.666),np.pi))
    bnds.append((np.arcsin(0.666),2*np.pi))

    #Minimise potential
    if bsh == True:
        result = opt.basinhopping(pt.fpot,x0=lvar,niter=int(it),callback=print_fun,
                               T=T,take_step=tritakestep,minimizer_kwargs={"args":x0,
                               "method":"L-BFGS-B","bounds":bnds,'options':{'maxls'
                               :10000,'ftol':1e-15,'maxcor':100}})
    elif bsh == False:
        result = opt.minimize(pt.fpot,x0=lvar,method="L-BFGS-B",bounds=bnds,
                            args=x0,options={'maxls':1000,'ftol':1e-15,'maxcor':10})
        print(result.message)

    opt_var = result.x
    en = result.fun
    print("\nMinimum found: E = %f eV"%en)
    opt_var = basis_change.l_c(opt_var)

    return opt_var

if __name__ == "__main__":

    unpk()
